title: Lemiffe
tagline: Music, Software, Stories & AI
description: "Welcome to lemiffe.com, powered by Jekyll and Lanyon, you'll find my legacy blog here as well as links to my main online locations!"
#url: https://lemiffe.com
baseurl: '/lemiffe.com/'
paginate: 5
paginate_path: /blog/page:num/
permalink: /:title

author:
    name: Lemiffe
    url: https://twitter.com/lemiffe

plugins:
    - jekyll-paginate

version: 1.1.0
google_analytics_id: #UA-XXXX-Y
